// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU3LIKCZhTq4CUOJAgEWQjRuYDPrfxgnU',
    appId: '1:144308298707:web:f6ac85a5a566dbc5190526',
    messagingSenderId: '144308298707',
    projectId: 'secret-picture2-app',
    authDomain: 'secret-picture2-app.firebaseapp.com',
    storageBucket: 'secret-picture2-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkYtHfZ6gvjpkMa4NptipaST29USV7D4',
    appId: '1:144308298707:android:1aadbcd1321baaaa190526',
    messagingSenderId: '144308298707',
    projectId: 'secret-picture2-app',
    storageBucket: 'secret-picture2-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQGgxu-bNIWT_0nxoAqGpWFz6a2ryRDY',
    appId: '1:144308298707:ios:93dd1303c928f869190526',
    messagingSenderId: '144308298707',
    projectId: 'secret-picture2-app',
    storageBucket: 'secret-picture2-app.appspot.com',
    iosClientId: '144308298707-627jqhko46k77pv8fla2pos50gbu6nsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretPicture2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQGgxu-bNIWT_0nxoAqGpWFz6a2ryRDY',
    appId: '1:144308298707:ios:93dd1303c928f869190526',
    messagingSenderId: '144308298707',
    projectId: 'secret-picture2-app',
    storageBucket: 'secret-picture2-app.appspot.com',
    iosClientId: '144308298707-627jqhko46k77pv8fla2pos50gbu6nsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretPicture2App',
  );
}
